### ISSUE TITLE
On submitting the wrong city or country name page is not showing anything

### ISSUE THREAD

**Issue by avinashji1302** [avinashji1302/Weather_Application_Using_Realtime_API#1]
# Page is getting blank on wrong submmision of city or country name

**Comment by avinashji1302** [comment]
> #Page is getting blank on wrong submmision of city or country name

**Comment by anmol111pal** [comment]
Hey, @avinashji1302 , I can work on this.

**Comment by anmol111pal** [comment]
@avinashji1302 , plz close the issue as it has been solved/fixed

**Comment by avinashji1302** [comment]
> @avinashji1302 , plz close the issue as it has been solved/fixed

Sorry...was a little busy

**Comment by avinashji1302** [comment]
Solved
