### ISSUE TITLE
HIgh & Low temperature showing same value. How's it possible ?

### ISSUE THREAD

**Issue by anmol111pal** [avinashji1302/Weather_Application_Using_Realtime_API#13]
### While entering the city name : Agra, country name: India.
The temperature is showing the same values for High & Low.

This behaviour is experienced with other city names as well.

### Screenshot:  
<img width="509" alt="bug in api" src="https://github.com/avinashji1302/Weather_Application_Using_Realtime_API/assets/93645325/33e40a53-dba0-4315-9da4-bde3744ed74a">

**Comment by avinashji1302** [comment]
> ### While entering the city name : Agra, country name: India.
> The temperature is showing the same values for High & Low.
> 
> This behaviour is experienced with other city names as well.
> 
> ### Screenshot:
> <img alt="bug in api" width="509" src="https://user-images.githubusercontent.com/93645325/254147192-33e40a53-dba0-4315-9da4-bde3744ed74a.png">


##  Thank You @anmol111pal  for Raising the issue

**Comment by MRodriguez-M** [comment]
Hi, can you please assign this to me? I would like to work on this issue

**Comment by avinashji1302** [comment]
> Hi, can you please assign this to me? I would like to work on this issue

Yes @MRodriguez-M  go ahead !

**Comment by MRodriguez-M** [comment]
@avinashji1302 @anmol111pal What other cities/countries also produced this issue? I checked with a few examples and only Agra, India had this bug

**Comment by anmol111pal** [comment]
> @avinashji1302 @anmol111pal What other cities/countries also produced this issue? I checked with a few examples and only Agra, India had this bug

I checked on Dehradun as well.

**Comment by avinashji1302** [comment]
> @avinashji1302 @anmol111pal What other cities/countries also produced this issue? I checked with a few examples and only Agra, India had this bug

I checked code and there is no problem with code...Data is coming from the API so problem is with API and we can't do it anything.....
So i am going to close this issue!

**Comment by avinashji1302** [comment]
Resolved
