### ISSUE TITLE
change the background color and make it more catchy

### ISSUE THREAD

**Issue by avinashji1302** [avinashji1302/Weather_Application_Using_Realtime_API#2]

**Comment by Aneal07** [comment]
Can you assign me this? please?

**Comment by avinashji1302** [comment]
> Can you assign me this? please?

Yes @Aneal07  , let me assign you!

**Comment by pulkitxm** [comment]
Can I get assigned? let me know how to start.

**Comment by shivam0277** [comment]
i would like to work on this issue could you please assign it to me ?

**Comment by avinashji1302** [comment]
@Pulkitxm and @shivam0277  This is issue already assigned and someone is working on it....You can find some new issues like typo or responisivenss and some issues are there  ....I will upload a project and that contain that the lot of good first issues...You can also contribute there
