### ISSUE TITLE
add support for Fahrenheit  

### ISSUE THREAD

**Issue by DavidKozdra** [avinashji1302/Weather_Application_Using_Realtime_API#9]
add a check input for Fahrenheit
should be a simple conversion 

// Fahrenheit to Celsius conversion
function fahrenheitToCelsius(fahrenheit) {
  return (fahrenheit - 32) * 5 / 9;
}

// Celsius to Fahrenheit conversion
function celsiusToFahrenheit(celsius) {
  return (celsius * 9 / 5) + 32;
}

on click 
   set to state of f 
   
   or c based on toggle state

**Comment by avinashji1302** [comment]
Thank You @DavidKozdra  for raising this issue!

**Comment by DavidKozdra** [comment]
currently working on this should be 15 more mins

**Comment by DavidKozdra** [comment]
lol took a long time cause my computer is being really slow sorry PR made https://github.com/avinashji1302/Weather_Application_Using_Realtime_API/pull/10
